### ISSUE TITLE
如何查看压缩后的文件大小来计算压缩率？

### ISSUE THREAD

**Issue by 2020lty** [DDDCai/imDedup_plus#1]
我成功编译运行项目，但是把一个文件夹下面还是文件夹，然后里面是JPEG图片，进行压缩，有结果，但是我不知道看哪个数据来得到传统意义的压缩率，就是压缩前的图像（JPEG）/压缩后的图像

**Comment by 2020lty** [comment]
文件里面给的compress ratio 是compression ratio   :  %f : 1\n",(double)(rawSize-undecodeSize)/finalSize);但是这个rawsize好像并不是原来JPEG文件大小，应该是解码后的，那是不是我应该看finalsize+undecodeSize是压缩后的结果？

**Comment by DDDCai** [comment]
> 文件里面给的compress ratio 是compression ratio : %f : 1\n",(double)(rawSize-undecodeSize)/finalSize);但是这个rawsize好像并不是原来JPEG文件大小，应该是解码后的，那是不是我应该看finalsize+undecodeSize是压缩后的结果？

这个rawsize就是原始JPEG的大小。undecodeSize指的是无法被成功解JPEG的图像，比如出错误的图像数据、非JPEG图像，减去它是为了将这些非正常的JPEG因素排除在统计中。

**Comment by DDDCai** [comment]
这个rawsize就是原始JPEG的大小。undecodeSize指的是无法被成功解JPEG的图像，比如出错误的图像数据、非JPEG图像，减去它是为了将这些非正常的JPEG因素排除在统计中。

**Comment by 2020lty** [comment]
您好，我按照仓库里面的方法生成图片，就是给一张图加水印，然后一个文件夹里面都是这张图加水印图片，然后得到的压缩率有3、4这么多，但是我看文章上说只有1.3不到的压缩率，这个正常吗，finalsize是这个文件夹得到的压缩后的文件吗？然后就是我在output路径里面会得到一个0文件夹，里面应该是特征最多的那个图片，然后还有一个0.idp体积很小，那个0.idp是什么呢，是整个文件夹图片的压缩吗？然后我想得到每次压缩的压缩率就用给的公式就可以了吗？如果可以，可以加我q2621507421，方便以后交流，或者就邮件交流。谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DDDCai/imDedup_plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月6日(星期一) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DDDCai/imDedup_plus] 如何查看压缩后的文件大小来计算压缩率？ (Issue #1)





 
这个rawsize就是原始JPEG的大小。undecodeSize指的是无法被成功解JPEG的图像，比如出错误的图像数据、非JPEG图像，减去它是为了将这些非正常的JPEG因素排除在统计中。

**Comment by 2020lty** [comment]
您好，我按照仓库里面的方法生成图片，就是给一张图加水印，然后一个文件夹里面都是这张图加水印图片，然后得到的压缩率有3、4这么多，但是我看文章上说只有1.3不到的压缩率，这个正常吗，finalsize是这个文件夹得到的压缩后的文件吗？然后就是我在output路径里面会得到一个0文件夹，里面应该是特征最多的那个图片，然后还有一个0.idp体积很小，那个0.idp是什么呢，是整个文件夹图片的压缩吗？然后我想得到每次压缩的压缩率就用给的公式就可以了吗？

**Comment by DDDCai** [comment]
如果只有这两个图片，这个压缩率看起来不是很正常。finalSize就是去重后的总大小。文件夹里放的图片，detector找不到与其相似的图片，它们将作为Idelta的base文件。每个文件夹都有一个同名的idp文件，idp文件保存的就是被Idelta压缩的target文件，imdedup将其压缩后的数据打包成一个idp保存，主要是为了减少频繁写小文件导致的I/O。压缩率我都在main函数里打印出来了。

**Comment by 2020lty** [comment]
我是使用几十张都是给一张照片加水印的，这几十张就只有水印部分不同，然后进行压缩，他显示压缩率就是特别高，请问这个时候压缩率代表的是整个文件夹的吗，还是怎么样，正确的压缩流程是使用两张不一样的有水印对吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月10日(星期五) 晚上8:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DDDCai/imDedup_plus] 如何查看压缩后的文件大小来计算压缩率？ (Issue #1)














 
如果只有这两个图片，这个压缩率看起来不是很正常。finalSize就是去重后的总大小。文件夹里放的图片，detector找不到与其相似的图片，它们将作为Idelta的base文件。每个文件夹都有一个同名的idp文件，idp文件保存的就是被Idelta压缩的target文件，imdedup将其压缩后的数据打包成一个idp保存，主要是为了减少频繁写小文件导致的I/O。压缩率我都在main函数里打印出来了。

**Comment by DDDCai** [comment]
哦，你用了几十张，那这个压缩率是正常的。压缩率是整个文件夹的压缩率。

**Comment by DDDCai** [comment]
我更新了代码和readme，你可以check一下，你可以通过先压缩，再尝试解压缩。如果解压缩通过了，那就说明没有问题。
